# Matrix Decomposition

## Outline
* Basic interpretation of matrix
* Basic definition
* Special matrices
* LU and QR decompositions
* Cholesky decomposition 
* Eigenvalue decomposition
* Singular Value Decomposition
  * Linear Regression 
* Principal Component Analysis**


## Basic Interpretations
* Matrices are both operands and operators at the same time.
* Matrix multipliction has several interpretations
  * element view
  * row view
  * column view
* Examples of matrices as operators

## Basic Definitions

### Eigenvector and Eigenvalues
**Definition** 
* An **eigenvector-eigenvalue pair** of a square matrix $A$ is a pair of a vector and scalar $(v,λ)$ for which $Av=λv$. 
* The **spectrum** of a matrix A is the set of all its eigenvalues.

We make the following observations.
1. The above definition implies that $(A−λI)v=0$.
2. The vector v can only be a solution of $(A−λI)v=0$ if $dimnull(A−λI)≥1$, implying that $(A−λI)$ is a singular matrix.
3. If v is an eigenvector of $A$, then so is $cv$ for all constant $c$. (with the same eigenvalue).


### Determinant
To define determinant, we first define **permutation** and **inversion of permutation**.

**Definition**
* A **permutation** of order $n$ is a one to one and onto function from ${1,…,n}$ to ${1,…,n}$. 
  * The product of two permutations $πσ$ is defined to be their function composition $π∘σ$. 
  * The set of all permutations of order n is denoted $\mathfrak{S}_n$.

**Definition** 
* A pair $a,b \in {1,…,n}$ and $a \ne b$ is an **inversion of a permutation** $σ \in \mathfrak{S}_n$ if $a < b$ but $σ(b) < σ(a)$. 
  * In other words, the function $σ$ reverses the natural order of $a$,$b$. 
  * The number of inversions of a permutation is called its **parity**. 
  * Permutations with an even parity are called even and permutations with an odd parity are called odd. 
  * The sign of a permutation $σ$, denoted $s(σ)$, equals 1 if $σ$ is even and -1 if $σ$ is odd.

**Definition** 
* The **determinant** of a square matrix $A \in R^{n×n}$ is defined as
$$
detA= \sum_{σ \in \mathfrak{S}_n} s(σ) A_{1,σ(1)} A_{2,σ(2)} ⋯ A_{n,σ(n)}.
$$

**Proposition**
* The determinant of a triangular matrix is the product of its diagonal elements.

**Proof**
* All permutation, except the one without change, will include at least one 0.

**Proposition**
* The following properties hold
1. $detI=1$.
2. $detA$ is a linear function of the $j-$column vector $v=(A_{1j},…,A_{nj})$ assuming other columns are held fixed.
3. If $A′$ is obtained from $A$ by interchanging two columns then $detA=−detA′$.
4. If A has two equal columns then $detA=0$.
5. $det(A)=det(A^⊤)$.

**Proposition**
* A square matrix is singular if and only if its determinant is zero.

**Definition**
* The characteristic polynomial of a square matrix A is the function
$$f(λ)=det(λI−A), \quad λ∈R$$.

**Observation**
* Since if $\lambda$ is an eigenvalue, then $A-\lambda I$ must be singular.  So if $\lambda$ is an eigenvalue, we have
$$f(λ)=det(λI−A) = 0.$$
That is, eigenvalues are the roots of the characteristic polynomial $f(\lambda)$.
* If $f(\lambda)$ is a polynomial of power $n$, and $\lambda_1, ..., \lambda_n$ are the $n$ roots of $f(x)$, then we have
$$ f(\lambda) = \prod_i (\lambda - \lambda_i)$$

### Trace
**Definition**
* The **trace** of a square matrix trace(A) is the sum of its diagonal elements.

**Proposition**
* The following properties hold:
$$trace(A+B)=trace(A)+trace(B)$$
$$trace(AB)=trace(BA)$$.

**Proof:**
$$trace(AB)= \sum_k \sum_j A_{kj} B_{jk} 
=\sum_k \sum_j B_{kj} A_{jk} = trace(BA)$$

**Definition: Frobenius norm**
* The **Frobenius norm** of a matrix A is the Euclidean norm of the vector obtained by concatenating the matrix columns into one long vector
$$ \parallel A \parallel_F = \sqrt{ \sum_i \sum_j A^2_{ij}} $$.

**Observation**
* Since the diagonal elements of $AA^⊤$ are the sum of squares of the rows of A, and the diagonal elements of $A^⊤A$ are the sum of squares of the columns of A, we have
$$ \parallel A \parallel_F = \sqrt{ trace(A A^T) }
= \sqrt{trace(A^T A)} $$

**Proposition**
* For any matrix $A$ and any orthogonal matrix $U$,
$$\parallel UA \parallel_F= \sqrt{(UA)^T(UA)} = \sqrt{A^TU^T UA}   =\parallel A \parallel_F$$.

**proposition** (Important!)
* If $A$ is a square matrix with eigenvalues $λ_i, i=1,…,n$
$$traceA=\sum_{i=1}^n λ_i $$
$$detA = \prod_{i=1}^n λ_i$$.

**Proof**
* **Value of determinant**: Since 
$$f(λ)=det(λI−A)= \prod_i (\lambda - \lambda_i)$$
If we substitute $\lambda = 0$ into the equation, we have
$$ f(0) = det(-A) = (-1)^n \prod_{i=1}^n \lambda_i$$
And
$$ det(A) = \prod_{i=1}^n \lambda_i $$
* **Value of trace**: First, we notice that for $det(λI−A)$ is a polynomial of $\lambda$ of order $n$, and the only time we can get $\lambda^{n-1}$ is from the expansion of the product of the diagonal $\prod_{i=1}^n(\lambda - A_{ii})$.  If we expand both sides of
$$ det(λI−A)= \prod_i (\lambda - \lambda_i),$$
and compare the coefficient of the $\lambda^{n-1}$ term on both sides, we will have
$$ trace(A) = \sum_i A_{ii} = \sum_i \lambda_i $$ 

## Special Matrices: Defintions



**Definition 1**
* A real matrix $A$ is a **symmetric matrix** if it equals to its own transpose, i.e., $A = A^T$.

**Definition 2**
* A complex matrix $A$ is a **hermitian matrix** if it equals to its own **complex conjugate transpose**, i.e., $A = A^H$.

**Definition 3**
* A real matrix $Q$ is an **orthogonal matrix** if the inverse of $Q$ equals to the transpose of $Q$, i.e., $Q^{−1} = Q^T$
  * From the definion, we have $QQ^T = Q^TQ = I$
  * In addition, expressing $Q=\begin{bmatrix} q_1 &q_2 &... &q_n\end{bmatrix}$, we know $\{q_1, q_2, ..., q_n\}$ is a set of orthonogal unit vectors that span $R^n$

**Definition 4** 
* A complex matrix $U$ is a **unitary matrix** if the inverse of $U$ equals the complex conjugate transpose of U, i.e., $U^{−1} = U^H$
  * Furthermore, $UU^H = U^HU = I$.

**Definition 5** 
* A matrix $A ∈ R^{n×n}$ is **positive definite** if $x^TAx > 0$ for all nonzero vector $x ∈ R^n$.
  * Positive definite matrices have positive definite principal sub-matrices 
  * All the diagonal entries are positive.

**Definition 6**
* Suppose $S ⊆ R^n$ be a subspace with orthonormal basis $V = (v_1, . . . , v_k)$, $P = V^TV ∈ R^{n×n}$
is the orthogonal projection matrix onto S such that $range(P) = S$, $P^2 = P$, and $P^T = P$. $P$ is unique for subspace $S$.

Note that hermitian matrix and unitary matrix for complex matrices are the counterparts of symmetric matrix and orthogonal matrix for real matrices.  In the following discussion.  We discuss only about real matrices.  The principles for complex matrices can be obtained by substituing hermitian and unitary matrix for symmetric and orthogonal matrix in the discussin.


## Matrix Decomposition: What is it?


* What: convert a matrix into multiplication of a number of matrices
  * $M = M_1 \times M_2 \times … \times M_n$
  * Usually $n$ is a small numbers: 2 or 3
  * There are many different way to decompose a matrix
    * Also called **matrix factorization**
* Purpose:
    * Some operation can be performed on the decomposed matrices more efficiently than performed on the original matrix


###LU Decomposition

* $A = LU$ (ideal case)
* $A = PLU$ ($P$ is a permutation matrix)
* $A = LDV$ 

where
* $L$ is a lower-triangle matrix, with diagonal all = 1
* $U$ is a upper-triangle matrix
* $D$ is a diagonal matrix (all 0 except on diagonal)


In [4]:
# LU decomposition
from numpy import array
from scipy.linalg import lu
# define a square matrix
A = array([[5, 2, 3], [4, 5, 6], [7, 17, 9]])
print(A)
# LU decomposition
P, L, U = lu(A)
print(P)
print(L)
print(U)
# reconstruct
B = P.dot(L).dot(U)
print(B)

[[ 5  2  3]
 [ 4  5  6]
 [ 7 17  9]]
[[0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]]
[[1.         0.         0.        ]
 [0.71428571 1.         0.        ]
 [0.57142857 0.46478873 1.        ]]
[[  7.          17.           9.        ]
 [  0.         -10.14285714  -3.42857143]
 [  0.           0.           2.45070423]]
[[ 5.  2.  3.]
 [ 4.  5.  6.]
 [ 7. 17.  9.]]


###QR Decomposition

* The QR decomposition is for m x n matrices
* $A = QR$
* $Q$ a (full) matrix with the size $m \times m$, and 
* $R$ is an upper triangle matrix with the size $m \times n$


In [0]:
# QR decomposition
from numpy import array
from numpy.linalg import qr
# define a 3x2 matrix
A = array([[1, 2], [3, 4], [5, 6]])
print(A)
# QR decomposition
Q, R = qr(A, 'complete')
print(Q)
print(R)
# reconstruct
B = Q.dot(R)
print(B)

[[1 2]
 [3 4]
 [5 6]]
[[-0.16903085  0.89708523  0.40824829]
 [-0.50709255  0.27602622 -0.81649658]
 [-0.84515425 -0.34503278  0.40824829]]
[[-5.91607978 -7.43735744]
 [ 0.          0.82807867]
 [ 0.          0.        ]]
[[1. 2.]
 [3. 4.]
 [5. 6.]]


###Cholesky Decomposition

* Assume matrix $A$ is a square symmetric matrices where all eigenvalues are greater than zero
  * That is, a **positive definite** symmetric matrices
* Then $A$ can be decomposed into $A = L L^T$
  * Where $L$ is a lower triangular matrix
  * By definition, $L^T$ must be an upper triangular matrix
* Why useful? Many matrix that occurs in nature are symmetric
* Cholesky decomposition is used for 
  * solving linear least squares for linear regression, 
  * simulation 
  * optimization methods


In [0]:
# Cholesky decomposition
from numpy import array
from numpy.linalg import cholesky
# define a 3x3 matrix
A = array([[2, 1, 1], [1, 2, 1], [1, 1, 2]])
print(A)
# Cholesky decomposition
L = cholesky(A)
print(L)
# reconstruct
B = L.dot(L.T)
print(B)

[[2 1 1]
 [1 2 1]
 [1 1 2]]
[[1.41421356 0.         0.        ]
 [0.70710678 1.22474487 0.        ]
 [0.70710678 0.40824829 1.15470054]]
[[2. 1. 1.]
 [1. 2. 1.]
 [1. 1. 2.]]


### Eigenvalue Decomposition (Eigen Decomposition)
Assume $A$ is an $n \times n$ matrix for which $n$ eigenvalue and eigenvector pairs exist, then we have:
$$Au = λ_iu, \quad \text{for } i=1, ..., n$$
Putting all these n equations together, into matrix form, we have:
$$AU = U\Lambda$$
Where $U$ is the matrix of all eigen vector, hence is a orthnormal matrix, and $\Lambda$ is a diagonal matrix with eigenvalues on its diagonal matrix. For an orthonormal matrix $U^{-1} = U^T$, therefore we have
$$ A = U \Lambda U^{-1} = U\lambda U^T$$

#### Diagonalization
From $ A = U\lambda U^T$, we have 
$$ \lambda = U^T A U$$
This is sometimes referred to as the **diagonalization of** $A$.


In [0]:
import numpy as np
from numpy import linalg as LA
w, v = LA.eig(np.diag((1, 2, 3)))  # a diagonal matrix [[1,0,0],[0,2,0],[0,0,3]]
print(w)
print(v)

[1. 2. 3.]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### Positive (semi-)definite matrix

A matrix $A$ is **positive definite**, if for all vector $x \in \mathbb{R^n}$,
$$ x^T A x > 0$$
$A$ is **positive semi-definite**, if for all vector $x \in \mathbb{R^n}$,
$$ x^T A x \ge 0$$

For a **positive semi-definite** $A$, the following three statements are equivalent:
1. For all vector $x \in \mathbb{R^n}$,
$$ x^T A x \ge 0$$
2. There exists some matrix $X$, such that 
$$ A = X X^T$$
3. For all eigenvalue $\lambda$ of $A$ 
$$ \lambda \ge 0$$

The eigen decomposition is quite useful for proving the equivalence of the above three statements.


### Singular Value Decomposition (SVD)
Let $M$ be an $m \times n$ matrix, $M$ can be decomposed into the form
$$\mathbf {M} =\mathbf {U} {\boldsymbol {\Sigma }}\mathbf {V} ^{T}$$
where
* $U$ is an $m \times m$ orthonormal matrix over K 
* $\Sigma$ is a diagonal $m × n$ matrix with non-negative real numbers on the diagonal
* $V$ is an $n \times n$ unitary matrix 

The diagonal entries $\sigma_i$ of $\Sigma$ are known as the singular values of $M$. 
  * A common convention is to list the singular values in descending order. 
  * In this case, the diagonal matrix, $\Sigma$, is uniquely determined by $M$ (though not the matrices $U$ and $V$ if $M$ is not square, see below).

In [5]:
import numpy as np
from numpy import array

# define a 3x3 matrix
A = array([[2, 1, 1, 2], [1, 2, 1, 3], [1, 1, 2, 4]])
u, s, vh = np.linalg.svd(A, full_matrices=True)
print(u)
print(s)
print(vh)

[[-0.44457749 -0.79729805  0.40824829]
 [-0.56842568 -0.10112162 -0.81649658]
 [-0.69227386  0.59505481  0.40824829]]
[6.65637106 1.30104737 1.        ]
[[-3.22976966e-01 -3.41582927e-01 -3.60188889e-01 -8.05773509e-01]
 [-8.45982198e-01 -3.10892967e-01  2.24196263e-01  3.70669285e-01]
 [ 4.08248290e-01 -8.16496581e-01  4.08248290e-01  6.66133815e-16]
 [ 1.15470054e-01 -3.46410162e-01 -8.08290377e-01  4.61880215e-01]]


## What does it mean?

### Singular Matrix Decomposition


**Recap:**
For any matrix $A \in R^{n \times m}$, we have
$$A=U \Sigma V^⊤$$
where
* $U \in R^{n×n}$ is an orthogonal matrix whose columns are the eigenvectors of $AA^⊤$
* $V \in R^{m×m}$ is an orthogonal matrix whose columns are the eigenvectors of $A^⊤A$
* $\Sigma \in R^{n×m}$ is an all zero matrix except for the first r diagonal elements $σ_i=\Sigma_{ii}, i=1,\ldots,r$ (called **singular values**) that are the square roots of the eigenvalues of $A^⊤A$ and of $AA^⊤$ (these two matrices have the same eigenvalues).

We assume above that the singular values are sorted in descending order and the eigenvectors are sorted according to descending order of their eigenvalues.

#### Prove SVD solution always exists

We assume in the proof below that n≥m. The case where $m>n$, we similarly by transposing $A$ into $A^⊤$.

**Proof:**
* Let $A$ be an $m \times n$ matrix. We prove that there exist orthogonal matrices, $U$ and $V$ of the appropriate size such that
$$U^TAV = \begin{pmatrix}
σ & 0 \\
0 & 0 \end{pmatrix}$$
where $\sigma$ is of the form
$$ σ = \begin{pmatrix}
σ_1 & & 0 \\
 &... & \\
0& &  σ_k
\end{pmatrix}$$
where $\sigma_i$ are the singular values of $A$, arranged in order of decreasing size.

* Since $A^TA$ is by definition a positive semi-definite matrix, we have
$$A^TAv_i = σ^2_i v_i$$ 
we arrange the eigenvalues in decreasing order, and have
$$σ^2_i \begin{cases}
> 0 &for\; i = 1, · · · , k, (σ_i > 0)\\
= 0 &for\; i > k
\end{cases}$$
Note that, for $i > k$, we also have $Av_i = 0$.
* For $i = 1, · · · , k$, we define $u_i \in F^m$ as 
$$u_i ≡ \frac{Av_i}{σ_i}$$
Equivalently, we can write $Av_i = σ_iu_i$.  
* Now
$$u_i^T u_j  = (σ^{−1}_i Av_i)^T (σ^{−1}_j Av_j)\\
=σ^{−1}_i σ^{−1}_j (v_i^T A^T A v_j) \\
=σ^{−1}_i σ^{−1}_j (v_i^T σ^2_j v_j) \\
=\frac{σ_j}{σ_i} v_i^T v_j = δ_{ij} .
$$
Thus $\{u_i\}^k_{i=1}$ is an orthonormal set of vectors in $F^m$. 
* Now, 
$$AA^Tu_i = \frac{1}{σ_i} AA^TAv_i = \frac{1}{σ_i} A σ^2_i v_i = σ^2_i u_i.$$
That is, $u_i$ are eigen vectors of $AA^T$ for $i=1,...k$.
* We extend $\{u_i\}^k_{i=1}$ to an orthonormal basis for all of $F^m$, by adding orthonormal vectors in the null space of $u_i$ for $i=1,...k$, and get
$\{u_i\}^m_{i=1}$.
* Let
$$\begin{align}
U &\equiv (u_1 · · · u_m), \; \text{and} \\
V &\equiv (v_1 · · · v_n) 
\end{align}$$
That is, $U$ is the matrix with $u_i$ as columns and $V$ is the matrix with $v_i$ as columns. Then
$$U^TAV = \begin{pmatrix}
u^T_1\\
. \\
. \\
. \\
u^T_k \\
. \\
. \\ 
. \\
u^T_m\end{pmatrix}
A 
\begin{pmatrix} v_1 · · · v_n \end{pmatrix} \\
= \begin{pmatrix}
u^T_1\\
. \\
. \\
. \\
u^T_k \\
. \\
. \\ 
. \\
u^T_m\end{pmatrix}
\begin{pmatrix}σ_1u_1 · · · σ_k u_k \, 0 · · · 0 \end{pmatrix} 
= \begin{pmatrix}
σ & 0 \\
0 & 0 \end{pmatrix}
$$
where $\sigma$ is given in the statement of the theorem. 

## Phyical Interpretation of SVD

* Given any data vector ${a_1}$, we can project it on some unit vector ${v_1}$ by doing 
$$ {a_1} \cdot {v_1} = s_{11} $$
* If we have two orthogonal unit vectors, and we want to project $a_1$ to these two vectors at one shot, we can express this as
$$ {a_1} \cdot [{v_1} v_2 ] = [s_{11} s_{12}] $$
* If we have many data vectors $a_1, a_2, ..., a_m$, and many orthogonal vectors$v_1, v_2, v_n$, we can do projections of all data points to all unit vectors at one shot:
$$\begin{bmatrix} a_1\\.\\ . \\a_m \end{bmatrix}
\begin{bmatrix} v_1 ... v_n \end{bmatrix} = 
\begin{bmatrix} s_{11} ... s_{1n} \\
... \\ s_{m1} ... s_{mn} 
\end{bmatrix}
$$
Write in matrix notation, we have:
$$ A V = S $$
* If we look at the columns of $S$, each one of them may have very different scales.  We can normalize it with the "length" of each column, so that it is easier to compare or to do other processing.  For each column $j$
$$ \begin{bmatrix} s_{1j} \\ . \\ . \\ s_{mj} \end{bmatrix}$$
we divide each element by its vector length $\sqrt{s_{1j}^2+...+s_{mj}^2}$.  We call this length $\sigma_j$.  Then, we have
$$ S = \begin{bmatrix} 
\frac{s_{11}}{\sigma_1} ... \frac{s_{1n}}{\sigma_n} \\
... \\ \frac{s_{m1}}{\sigma_1} ... \frac{s_{mn}}{\sigma_n}
\end{bmatrix}
\begin{bmatrix} \sigma_1 ... 0 \\
... \\ 0 ... \sigma_n 
\end{bmatrix} = U \Sigma
$$
That is, $ AV = U\Sigma$, and we have something very similar to SVD: $$A = U\Sigma V^T$$
* However, up to this point, we only assume that $V$ is a set of orthonormal vectors, and $U$ is normalized to become a set of unit vectors.  Note that
  * There can be infinite many sets of $V$.
  * At this point, we can use any set of $V$ that is useful for our purpose.  
  * The column vectors in $U$ though being unit vectors, are not necessarily orthogonal (independent) to one another.  That is, they are not orthonormal.
* If for our purpose, we want $U$ to be orthonormal, too, then we are looking for SVD. In this case, we have to find a particular set of $V$ that can enable $U$ to be orthonormal.  The theorem of singular value decomposition proves that that the solution always exist, and is a unique solution.  

## Essence of Principle Component Analysis (PCA)
In singular value decomposition, we have 
$$ A = U\Sigma V^T$$
where $\Sigma$ is an diagonal matrix, with the singular values order from big to small.  If we have a diagonal matrix 
$$ \Sigma = diag(\sigma_1, \sigma_2, ..., \sigma_n),$$
And the first few eigenvalues are much larger than the last few eigenvalues, we decide to approximate this diagonal matrix by setting the eigenvalues after index $k$ to be 0.  That is, we approximate $\Sigma$ by 
$$ \Sigma' = diag(\sigma_1, \sigma_2, ..., \sigma_k, 0, 0, ...)$$

This is the essence of principal component analysis.  