
## Broadcast rules

Broadcasting deals with operands that do not have exactly the same shape, so that functions can work on them in a meaningful way.

#### Rules of broadcasting:
1. If all input arrays do not have the same number of dimensions, a “1” will be repeatedly prepended to the shapes of the smaller arrays until all the arrays have the same number of dimensions.

2. arrays with a size of 1 along a particular dimension act as if they had the size of the array with the largest shape along that dimension. The value of the array element is assumed to be the same along that dimension for the “broadcast” array.

3. However, if two arrays have the same number of dimensions, but the sizes of a particular dimension are not the same, it is considered as error, and operation cannot proceed.

After application of the broadcasting rules, the sizes of all arrays must match. More details can be found in [Broadcasting section of the Numpy manual](https://docs.scipy.org/doc/numpy-1.16.1/user/basics.broadcasting.html).

Here are some examples:
```
array1 (3d array): 256 x 256 x 3
array2 (1d array):             3
Result (3d array): 256 x 256 x 3
```

```
A      (4d array):  8 x 1 x 6 x 1
B      (3d array):      7 x 1 x 5
Result (4d array):  8 x 7 x 6 x 5
```
```
A      (2d array):  5 x 4
B      (1d array):      1
Result (2d array):  5 x 4
```
```
A      (2d array):  5 x 4
B      (1d array):      4
Result (2d array):  5 x 4
```
```
A      (3d array):  15 x 3 x 5
B      (3d array):  15 x 1 x 5
Result (3d array):  15 x 3 x 5
```
```
A      (3d array):  15 x 3 x 5
B      (2d array):       3 x 5
Result (3d array):  15 x 3 x 5
```
```
A      (3d array):  15 x 3 x 5
B      (2d array):       3 x 1
Result (3d array):  15 x 3 x 5
```

Broadcast cannot proceed in the following examples

```
A      (1d array):  3
B      (1d array):  4 # trailing dimensions do not match
```
```
A      (2d array):      2 x 1
B      (3d array):  8 x 4 x 3 # second from last dimensions mismatched
```

In [0]:
# Some real examples
import numpy as np

x = np.arange(4)
y = np.ones(5)
z = np.ones((3,4))
print(x)
print(y)
print(z)

[0 1 2 3]
[1. 1. 1. 1. 1.]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [0]:
# x + y will cause an error
x + y

In [0]:
# if we transpose x, then it is OK
xx = x.reshape(4,1)
print("xx's shape is:", xx.shape)
print("y's shape is:", y.shape)
print(xx)
print(y)
print(xx+y)

xx's shape is: (4, 1)
y's shape is: (5,)
[[0]
 [1]
 [2]
 [3]]
[1. 1. 1. 1. 1.]
[[1. 1. 1. 1. 1.]
 [2. 2. 2. 2. 2.]
 [3. 3. 3. 3. 3.]
 [4. 4. 4. 4. 4.]]


In [0]:
# Another example
print(x.shape)
print(z.shape)
print((x + z).shape)

print(x)
print(z)
print(x + z)


(4,)
(3, 4)
(3, 4)
[0 1 2 3]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[1. 2. 3. 4.]
 [1. 2. 3. 4.]
 [1. 2. 3. 4.]]
